[build]
  functions = "./functions"

[[redirects]]
  from = "/"
  to = "/index.html"
  force = true
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false